// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: chatbot.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"` // rỗng -> tạo mới
	Content        string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                                     // prompt
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                         // lấy từ context auth nội bộ hoặc truyền trực tiếp
	OrgId          string                 `protobuf:"bytes,4,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`                            // optional
	Title          string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`                                         // optional khi tạo conv lần đầu
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_chatbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{0}
}

func (x *SendMessageRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SendMessageRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SendMessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type SendMessageReply struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ConversationId         string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	UserMessageId          string                 `protobuf:"bytes,2,opt,name=user_message_id,json=userMessageId,proto3" json:"user_message_id,omitempty"`
	AssistantMessageId     string                 `protobuf:"bytes,3,opt,name=assistant_message_id,json=assistantMessageId,proto3" json:"assistant_message_id,omitempty"`
	AssistantContent       string                 `protobuf:"bytes,4,opt,name=assistant_content,json=assistantContent,proto3" json:"assistant_content,omitempty"`
	ModelName              string                 `protobuf:"bytes,5,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	TokensInput            int32                  `protobuf:"varint,6,opt,name=tokens_input,json=tokensInput,proto3" json:"tokens_input,omitempty"`
	TokensOutput           int32                  `protobuf:"varint,7,opt,name=tokens_output,json=tokensOutput,proto3" json:"tokens_output,omitempty"`
	LatencyMs              int32                  `protobuf:"varint,8,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	UserMessageCreatedAtMs int64                  `protobuf:"varint,9,opt,name=user_message_created_at_ms,json=userMessageCreatedAtMs,proto3" json:"user_message_created_at_ms,omitempty"`
	AiMessageCreatedAtMs   int64                  `protobuf:"varint,10,opt,name=ai_message_created_at_ms,json=aiMessageCreatedAtMs,proto3" json:"ai_message_created_at_ms,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SendMessageReply) Reset() {
	*x = SendMessageReply{}
	mi := &file_chatbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageReply) ProtoMessage() {}

func (x *SendMessageReply) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageReply.ProtoReflect.Descriptor instead.
func (*SendMessageReply) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{1}
}

func (x *SendMessageReply) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *SendMessageReply) GetUserMessageId() string {
	if x != nil {
		return x.UserMessageId
	}
	return ""
}

func (x *SendMessageReply) GetAssistantMessageId() string {
	if x != nil {
		return x.AssistantMessageId
	}
	return ""
}

func (x *SendMessageReply) GetAssistantContent() string {
	if x != nil {
		return x.AssistantContent
	}
	return ""
}

func (x *SendMessageReply) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *SendMessageReply) GetTokensInput() int32 {
	if x != nil {
		return x.TokensInput
	}
	return 0
}

func (x *SendMessageReply) GetTokensOutput() int32 {
	if x != nil {
		return x.TokensOutput
	}
	return 0
}

func (x *SendMessageReply) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *SendMessageReply) GetUserMessageCreatedAtMs() int64 {
	if x != nil {
		return x.UserMessageCreatedAtMs
	}
	return 0
}

func (x *SendMessageReply) GetAiMessageCreatedAtMs() int64 {
	if x != nil {
		return x.AiMessageCreatedAtMs
	}
	return 0
}

type ListMessagesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Limit          int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMessagesRequest) Reset() {
	*x = ListMessagesRequest{}
	mi := &file_chatbot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesRequest) ProtoMessage() {}

func (x *ListMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListMessagesRequest) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{2}
}

func (x *ListMessagesRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMessagesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type MessageItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	ParentId       string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Role           string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // "user" | "assistant" | "tool"
	Content        string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ContentType    string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "text" | "markdown" | "json"
	TokensInput    int32                  `protobuf:"varint,7,opt,name=tokens_input,json=tokensInput,proto3" json:"tokens_input,omitempty"`
	TokensOutput   int32                  `protobuf:"varint,8,opt,name=tokens_output,json=tokensOutput,proto3" json:"tokens_output,omitempty"`
	LatencyMs      int32                  `protobuf:"varint,9,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	ModelName      string                 `protobuf:"bytes,10,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,11,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	CreatedAtMs    int64                  `protobuf:"varint,12,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageItem) Reset() {
	*x = MessageItem{}
	mi := &file_chatbot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageItem) ProtoMessage() {}

func (x *MessageItem) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageItem.ProtoReflect.Descriptor instead.
func (*MessageItem) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{3}
}

func (x *MessageItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MessageItem) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *MessageItem) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *MessageItem) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MessageItem) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MessageItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *MessageItem) GetTokensInput() int32 {
	if x != nil {
		return x.TokensInput
	}
	return 0
}

func (x *MessageItem) GetTokensOutput() int32 {
	if x != nil {
		return x.TokensOutput
	}
	return 0
}

func (x *MessageItem) GetLatencyMs() int32 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *MessageItem) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *MessageItem) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *MessageItem) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

type ListMessagesReply struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ConversationId string                 `protobuf:"bytes,1,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	Total          int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Items          []*MessageItem         `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListMessagesReply) Reset() {
	*x = ListMessagesReply{}
	mi := &file_chatbot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessagesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessagesReply) ProtoMessage() {}

func (x *ListMessagesReply) ProtoReflect() protoreflect.Message {
	mi := &file_chatbot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessagesReply.ProtoReflect.Descriptor instead.
func (*ListMessagesReply) Descriptor() ([]byte, []int) {
	return file_chatbot_proto_rawDescGZIP(), []int{4}
}

func (x *ListMessagesReply) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *ListMessagesReply) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListMessagesReply) GetItems() []*MessageItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_chatbot_proto protoreflect.FileDescriptor

const file_chatbot_proto_rawDesc = "" +
	"\n" +
	"\rchatbot.proto\x12\x02pb\"\x9d\x01\n" +
	"\x12SendMessageRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x15\n" +
	"\x06org_id\x18\x04 \x01(\tR\x05orgId\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\"\xbc\x03\n" +
	"\x10SendMessageReply\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12&\n" +
	"\x0fuser_message_id\x18\x02 \x01(\tR\ruserMessageId\x120\n" +
	"\x14assistant_message_id\x18\x03 \x01(\tR\x12assistantMessageId\x12+\n" +
	"\x11assistant_content\x18\x04 \x01(\tR\x10assistantContent\x12\x1d\n" +
	"\n" +
	"model_name\x18\x05 \x01(\tR\tmodelName\x12!\n" +
	"\ftokens_input\x18\x06 \x01(\x05R\vtokensInput\x12#\n" +
	"\rtokens_output\x18\a \x01(\x05R\ftokensOutput\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\b \x01(\x05R\tlatencyMs\x12:\n" +
	"\x1auser_message_created_at_ms\x18\t \x01(\x03R\x16userMessageCreatedAtMs\x126\n" +
	"\x18ai_message_created_at_ms\x18\n" +
	" \x01(\x03R\x14aiMessageCreatedAtMs\"l\n" +
	"\x13ListMessagesRequest\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"\xfd\x02\n" +
	"\vMessageItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12!\n" +
	"\ftokens_input\x18\a \x01(\x05R\vtokensInput\x12#\n" +
	"\rtokens_output\x18\b \x01(\x05R\ftokensOutput\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\t \x01(\x05R\tlatencyMs\x12\x1d\n" +
	"\n" +
	"model_name\x18\n" +
	" \x01(\tR\tmodelName\x12\x1d\n" +
	"\n" +
	"error_code\x18\v \x01(\tR\terrorCode\x12\"\n" +
	"\rcreated_at_ms\x18\f \x01(\x03R\vcreatedAtMs\"y\n" +
	"\x11ListMessagesReply\x12'\n" +
	"\x0fconversation_id\x18\x01 \x01(\tR\x0econversationId\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12%\n" +
	"\x05items\x18\x03 \x03(\v2\x0f.pb.MessageItemR\x05items2\x8d\x01\n" +
	"\x0eChatbotService\x12;\n" +
	"\vSendMessage\x12\x16.pb.SendMessageRequest\x1a\x14.pb.SendMessageReply\x12>\n" +
	"\fListMessages\x12\x17.pb.ListMessagesRequest\x1a\x15.pb.ListMessagesReplyB\x05Z\x03/pbb\x06proto3"

var (
	file_chatbot_proto_rawDescOnce sync.Once
	file_chatbot_proto_rawDescData []byte
)

func file_chatbot_proto_rawDescGZIP() []byte {
	file_chatbot_proto_rawDescOnce.Do(func() {
		file_chatbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatbot_proto_rawDesc), len(file_chatbot_proto_rawDesc)))
	})
	return file_chatbot_proto_rawDescData
}

var file_chatbot_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_chatbot_proto_goTypes = []any{
	(*SendMessageRequest)(nil),  // 0: pb.SendMessageRequest
	(*SendMessageReply)(nil),    // 1: pb.SendMessageReply
	(*ListMessagesRequest)(nil), // 2: pb.ListMessagesRequest
	(*MessageItem)(nil),         // 3: pb.MessageItem
	(*ListMessagesReply)(nil),   // 4: pb.ListMessagesReply
}
var file_chatbot_proto_depIdxs = []int32{
	3, // 0: pb.ListMessagesReply.items:type_name -> pb.MessageItem
	0, // 1: pb.ChatbotService.SendMessage:input_type -> pb.SendMessageRequest
	2, // 2: pb.ChatbotService.ListMessages:input_type -> pb.ListMessagesRequest
	1, // 3: pb.ChatbotService.SendMessage:output_type -> pb.SendMessageReply
	4, // 4: pb.ChatbotService.ListMessages:output_type -> pb.ListMessagesReply
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatbot_proto_init() }
func file_chatbot_proto_init() {
	if File_chatbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatbot_proto_rawDesc), len(file_chatbot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatbot_proto_goTypes,
		DependencyIndexes: file_chatbot_proto_depIdxs,
		MessageInfos:      file_chatbot_proto_msgTypes,
	}.Build()
	File_chatbot_proto = out.File
	file_chatbot_proto_goTypes = nil
	file_chatbot_proto_depIdxs = nil
}
